config/routes.rb
Todos::Application.routes.draw do
  get "welcome/index"

  resources :todo_groups do
    resources :todos
  end

  root 'welcome#index'

end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :todo_group
  # validates :title, uniqueness: true

end

app/models/todo_group.rb
class TodoGroup < ActiveRecord::Base
  has_many :todos, dependent: :destroy

  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todo_groups_controller.rb
class TodoGroupsController < ApplicationController
  before_filter :set_group, only: [:show, :edit, :upate, :destroy]

  def index
    @todo_groups = TodoGroup.all
  end

  def new
    @todo_group = TodoGroup.new
  end

  def create
    @todo_group = TodoGroup.new(group_params)

    respond_to do |format|
      if @todo_group.save
        format.html { redirect_to @todo_group, notice: 'Group was successfully created.' }
        format.json { render action: 'show', status: :created, location: @todo_group }
      else
        format.html { render action: 'new' }
        format.json { render json: @todo_group.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def show
  end

  private
    def set_group
      @todo_group = TodoGroup.find_by_id(params[:id])
    end

    def group_params
      params.require(:todo_group).permit(:name)
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  # before_action :set_todo, only: [:show, :edit, :update, :destroy]
  before_action :set_todo_group, only: [:index, :create, :show, :edit, :update, :destroy]

  # GET /todos
  # GET /todos.json
  def index
    # raise params.inspect
    Rails.logger.debug("#{params.inspect}")
    # Rails.logger.debug("#{todo_group.inspect}")
    @todos = @group.todos
    # @todos = Todo.all
  end

  # GET /todos/1
  # GET /todos/1.json
  def show
  end

  # GET /todos/new
  def new
    @todo = @group.todos.build
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos
  # POST /todos.json
  def create
    @todo = @group.todos.build(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render action: 'show', status: :created }
      else
        format.html { render action: 'new' }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    @todo = @group.todos.find(params[:id])
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    @todo = @group.todos.find(params[:id])
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    def set_todo_group
      @group = TodoGroup.find(params[:todo_group_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_params
      params.require(:todo).permit(:title, :complete, :todo_group_id)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_groups_helper.rb
module TodoGroupsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="app">
<head>
  <title>Todos</title>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/restangular/1.3.1/restangular.min.js"></script>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <!-- <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  </div> -->

  <div class="container theme-showcase" role="main">
    <%= yield %>
  </div>

</body>
</html>

app/views/todo_groups/new.html.erb
<h1>New todo group</h1>

<%= render 'form' %>

<%= link_to 'Back', todo_groups_path %>

app/views/todos/_form.html.erb
<%= form_for(@todo) do |f| %>
  <% if @todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
      <% @todo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :complete %><br>
    <%= f.check_box :complete %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todos/edit.html.erb
<h1>Editing todo</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/new.html.erb
<h1>New todo</h1>

<%= render 'form' %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @todo.title %>
</p>

<p>
  <strong>Complete:</strong>
  <%= @todo.complete %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>

app/views/welcome/index.html.erb
<div class="row" ng-controller="GroupsCtrl">
  <div class="col-xs-3">
    <h1>Groups</h1>
    <div class="list-group todo-group">
      <a href="#" class="list-group-item" ng-class="{ active: g.id === currentGroup.id }"
        ng-repeat="g in groups"
        ng-click="setCurrentGroup($event, g)">
        {{ g.name }}
      </a>

      <form ng-submit="addGroup($event)">
        <input type="text" class="form-control" ng-model="nextGroup"
          placeholder="Add new group...">
      </form>
    </div>
  </div>

  <div class="col-xs-6" ng-controller="TodosCtrl" ng-show="visible()">
    <h1>Todos</h1>
    <form ng-submit="addTodo($event)">
      <input type="text" class="form-control" ng-model="nextTodo.title"
        placeholder="Add new todo...">
    </form>

    <div class="panel panel-default">
      <p class="todo-filters-content">
        All: {{(todos).length}},
        Completed: {{(todos|filter:{complete: true}).length}}
      </p>
      <div class="panel-body">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Todo to search...." ng-model="query">
          <span class="input-group-btn">
            <button class="btn btn-default" type="button"><span class="glyphicon glyphicon-search"></span></button>
          </span>
        </div>

        <table class="table">
          <thead></thead>
          <tbody class="todos">
            <tr ng-repeat="todo in todos | filter: { title: query }">
              <td ng-class="{complete: todo.complete}">
                <input type="checkbox" ng-click="toggleComplete($index, todo)"
                  ng-model="todo.complete">

                <form ng-submit="editTodo($event, $index, todo)" ng-show="todo.editable" >
                  <input type="text" class="editable" placeholder="{{todo.title}}"
                    ng-model="todo.title">
                </form>

                <span ng-show="!todo.editable">{{todo.title}}</span>
              </td>
    <!--  Q: how to make show link work here. -->
              <td>
                <%= link_to "", "#", ng_click: "toggleEditable($event, todo)",
                  class: "glyphicon glyphicon-pencil" %>
                <%= link_to "", "#", ng_click: "removeTodo($event, $index, todo)",
                  class: "glyphicon glyphicon-remove" %>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <div class="debug-information panel panel-default">
      <div class="panel-heading">Debug Information</div>
      <div class="panel-body">
        <h6>todos</h6>
        <p class="text-info">{{ todos | json}}</p>
        <h6>group</h6>
        <p class="text-info">{{ group | json}}</p>
      </div>
    </div>
  </div>
</div>